const TICKER_MAP = {
  // Big pharma parents (subsidiary → parent ticker)
  "janssen biotech": "JNJ",
  "janssen biotech, inc.": "JNJ",
  "janssen pharmaceuticals": "JNJ",
  "janssen pharmaceuticals, inc.": "JNJ",
  "johnson & johnson": "JNJ",
  "genentech": "RHHBY",
  "genentech, inc.": "RHHBY",
  "genentech usa, inc.": "RHHBY",
  "hoffmann-la roche": "RHHBY",
  "f. hoffmann-la roche": "RHHBY",
  "roche": "RHHBY",
  "pfizer": "PFE",
  "pfizer inc.": "PFE",
  "pfizer inc": "PFE",
  "merck": "MRK",
  "merck & co.": "MRK",
  "merck sharp & dohme": "MRK",
  "merck sharp & dohme llc": "MRK",
  "novartis": "NVS",
  "novartis pharmaceuticals": "NVS",
  "novartis pharmaceuticals corporation": "NVS",
  "novartis gene therapies": "NVS",
  "astrazeneca": "AZN",
  "astrazeneca pharmaceuticals": "AZN",
  "astrazeneca pharmaceuticals lp": "AZN",
  "medimmune": "AZN",
  "alexion pharmaceuticals": "AZN",
  "sanofi": "SNY",
  "sanofi-aventis": "SNY",
  "sanofi-aventis u.s.": "SNY",
  "genzyme": "SNY",
  "gsk": "GSK",
  "glaxosmithkline": "GSK",
  "glaxosmithkline llc": "GSK",
  "viiv healthcare": "GSK",
  "bristol-myers squibb": "BMY",
  "bristol-myers squibb company": "BMY",
  "celgene": "BMY",
  "eli lilly": "LLY",
  "eli lilly and company": "LLY",
  "lilly": "LLY",
  "bayer": "BAYRY",
  "bayer healthcare": "BAYRY",
  "bayer healthcare pharmaceuticals": "BAYRY",
  "boehringer ingelheim": null,
  "boehringer ingelheim pharmaceuticals": null,
  "boehringer ingelheim pharmaceuticals, inc.": null,
  "takeda": "TAK",
  "takeda pharmaceuticals": "TAK",
  "takeda pharmaceuticals u.s.a.": "TAK",
  "takeda pharmaceuticals u.s.a., inc.": "TAK",
  "abbvie": "ABBV",
  "abbvie inc.": "ABBV",
  "allergan": "ABBV",
  "amgen": "AMGN",
  "amgen inc.": "AMGN",
  "biogen": "BIIB",
  "biogen inc.": "BIIB",
  "biogen idec": "BIIB",
  "gilead": "GILD",
  "gilead sciences": "GILD",
  "gilead sciences, inc.": "GILD",
  "vertex": "VRTX",
  "vertex pharmaceuticals": "VRTX",
  "vertex pharmaceuticals incorporated": "VRTX",
  "regeneron": "REGN",
  "regeneron pharmaceuticals": "REGN",
  "regeneron pharmaceuticals, inc.": "REGN",

  // Pure-play biotechs
  "replimune": "REPL",
  "replimune, inc.": "REPL",
  "aldeyra": "ALDX",
  "aldeyra therapeutics": "ALDX",
  "aldeyra therapeutics, inc.": "ALDX",
  "fresenius kabi": "FSNUY",
  "fresenius kabi usa": "FSNUY",
  "fresenius kabi usa, llc": "FSNUY",
  "chiesi": null,
  "chiesi farmaceutici": null,
  "chiesi farmaceutici s.p.a": null,
  "atara": "ATRA",
  "atara biotherapeutics": "ATRA",
  "atara biotherapeutics, inc.": "ATRA",
  "sarepta": "SRPT",
  "sarepta therapeutics": "SRPT",
  "bluebird bio": "BLUE",
  "bluebird bio, inc.": "BLUE",
  "moderna": "MRNA",
  "moderna inc.": "MRNA",
  "modernatx": "MRNA",
  "bioxcel": "BTAI",
  "bioxcel therapeutics": "BTAI",
  "intellia": "NTLA",
  "intellia therapeutics": "NTLA",
  "crispr therapeutics": "CRSP",
  "editas": "EDIT",
  "editas medicine": "EDIT",
  "beam": "BEAM",
  "beam therapeutics": "BEAM",
  "kymera": "KYMR",
  "kymera therapeutics": "KYMR",
  "arcus": "RCUS",
  "arcus biosciences": "RCUS",
  "cytokinetics": "CYTK",
  "cytokinetics incorporated": "CYTK",
  "ionis": "IONS",
  "ionis pharmaceuticals": "IONS",
  "alnylam": "ALNY",
  "alnylam pharmaceuticals": "ALNY",
  "blueprint medicines": "BPMC",
  "blueprint medicines corporation": "BPMC",
};

export function lookupTicker(companyName) {
  const normalized = companyName.trim().replace(/\s+/g, " ").toLowerCase();
  if (Object.prototype.hasOwnProperty.call(TICKER_MAP, normalized)) {
    return TICKER_MAP[normalized];
  }
  return undefined;
}
